apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-apps-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: common-apps
            namespace: common-apps
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/rmallam/frappe-gitops.git
        targetRevision: main
        path: '{{name}}'  # Path to your Helm chart
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 1m
            factor: 2
        syncOptions:
          - Validate=true
          - CreateNamespace=true