mariadb:
  enabled: false 
dbHost: "common-db-instance.common-apps"
dbPort: "3306"
dbRootUser: "root"
dbRootPassword: "foo123"

redis-cache:
  enabled: false
  host: "redis://redis-socketio-master.common-apps:6379"
redis-queue:
  enabled: false
  host: "redis://redis-queue-master.common-apps:6379"
ingress:
  enabled: true
  ingressName: "erp-customer1.kube.themallams.com"
  annotations:        
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
  - host: erp-customer1.kube.themallams.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
   - secretName: erp-tls
     hosts:
       - erp-customer1.kube.themallams.com

persistence:
  worker:
    storageClass: "nfs-rwx-storage"
jobs:
  createSite:
    enabled: true
    siteName: "erp-customer1.kube.themallams.com"
    adminPassword: "Welcome123@"
    installApps:
      - erpnext
  dropSite:
    enabled: false
    forced: false
    siteName: "erp-customer1.kube.themallams.com"
    backoffLimit: 0
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}