apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frappe
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rmallam/frappe-gitops.git'
    targetRevision: HEAD
    path: frappe/erpnext
    helm:
      valueFiles:
        -  values-custom.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: erpnext
  syncPolicy:
    automated: {}
