apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rmallam/frappe-gitops.git'
    targetRevision: HEAD
    path: frappe/erpnext
    helm:
      valueFiles:
        -  values-customer2.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: customer2
  syncPolicy:
    automated: {}
    syncOptions:
      - Validate=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /status
        - /metadata
        - /spec
