name: Digital Ocean K8s Cluster Lifecycle

on:
  # Allow manual triggering for testing
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (create or delete)'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - delete

jobs:
  cluster-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Check if cluster already exists
        id: check-cluster
        run: |
          echo "Checking if cluster 'rmk8s' already exists..."
          if doctl kubernetes cluster get rmk8s &> /dev/null; then
            echo "Cluster 'rmk8s' already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "CLUSTER_NAME=rmk8s" >> $GITHUB_ENV
          else
            echo "Cluster 'rmk8s' does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create K8s cluster
        if: github.event.inputs.action == 'create' && steps.check-cluster.outputs.exists == 'false'
        run: |
          echo "Creating Digital Ocean Kubernetes cluster..."
          doctl k c c rmk8s \
            --node-pool "name=example-pool;size=s-2vcpu-4gb;count=1;auto-scale=true;min-nodes=1;max-nodes=3"
          echo "Cluster created successfully!"
          echo "CLUSTER_NAME=rmk8s" >> $GITHUB_ENV

      - name: Checkout repository
        if: github.event.inputs.action == 'create'
        uses: actions/checkout@v3
      
      - name: Wait for cluster to be ready
        if: github.event.inputs.action == 'create' && steps.check-cluster.outputs.exists == 'false'
        run: |
          echo "Waiting for the Digital Ocean Kubernetes cluster to be ready..."
          # Poll the cluster status until it's ready
          while true; do
            STATUS=$(doctl kubernetes cluster get rmk8s --format Status --no-header)
            echo "Current cluster status: $STATUS"
            if [[ "$STATUS" == "running" ]]; then
              echo "Cluster is now ready!"
              break
            fi
            echo "Waiting for cluster to become ready..."
            sleep 30
          done
      
      - name: Setup kubectl
        if: github.event.inputs.action == 'create'
        run: |
          doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}
      
      - name: Install ArgoCD using script
        if: github.event.inputs.action == 'create'
        run: |
          chmod +x ./scripts/install-argo.sh
          ./scripts/install-argo.sh
          echo "ArgoCD installation completed via script"
      
      - name: Apply cluster prerequisites
        if: github.event.inputs.action == 'create'
        run: |
          echo "Applying cluster prerequisites..."
          kubectl apply -f cluster-pre-req-appset.yaml
          echo "Cluster prerequisites applied"
      
      - name: Wait for operators to come up
        if: github.event.inputs.action == 'create'
        run: |
          echo "Waiting for operators to come up (10 minutes)..."
          
          # Wait for any applications created by the appset to become healthy
          # First, wait for the applications to be created
          sleep 60
          
          # Check all applications status
          kubectl get applications -n argocd
          
          # Wait for up to 10 minutes total with progress updates
          for i in {1..10}; do
            echo "Waiting for operators - $i minutes passed..."
            sleep 60
            kubectl get applications -n argocd
          done
          
          echo "Cluster should be ready with all prerequisites installed"
      
      - name: Apply common-apps-appset
        if: github.event.inputs.action == 'create'
        run: |
          echo "Applying common-apps ApplicationSet..."
          kubectl apply -f common-apps-appset.yaml
          echo "Common apps ApplicationSet applied"
      
      - name: Delete K8s cluster
        if: github.event.inputs.action == 'delete'
        run: |
          echo "Deleting Digital Ocean Kubernetes cluster..."
          doctl k cluster delete rmk8s --force
          echo "Cluster deleted successfully!"